### PR TITLE
Add spans data schema

### PR DESCRIPTION
**Pull request by dbanda**
Add spans data schema. This can help us validate messages in the spans data bag.

Also:
* Fixed typo in the readme
* Add title to the top level transaction message

### CODE REVIEW

**Comment by lynnagara** [comment]
Is there a reason why all the spans/starfish experiments has to be on the transactions topic still, and we are not creating a separate one for the new pipeline?

**Comment by dbanda** [comment]
> Is there a reason why all the spans/starfish experiments has to be on the transactions topic still

@lynnagara eventually we will have spans on a new topic and ultimately spans will replace transactions. But right now, we decided to leave it there as we iterate. My understanding is starfish wants to test things and move fast. The issue is that we are stuffing a lot of things in the spans data bag and don't have any checking on it. I could create a separate schema for `SpansData`, but that would have to mean adding some customized code within the spans consumer to check the data field. Either way if fine with me, but I would like to have a schema defined somewhere so that we have a unified source of truth and catch typing bugs.

**Comment by untitaker** [comment]
We have had a similar problem already. I think long-term we might want to have specialized schemas per consumer group.

>With all the schema changes that are going on, I think it's much safer to keep it separate.

The schemas are not changing. We are just parsing more/less data out of the same payloads.

What is more concerning to me is that we are trying to make sense of this data while there is absolutely zero validation for spans data in Relay. The next buggy SDK could take down a spans consumer that tries to assume anything about the payloads.

**Comment by lynnagara** [comment]
My concern was coming from a place mostly unrelated to this schema change. I'm just not sure it's a good idea to build and iterate fast on things inside the existing pipeline just because it's "faster". Though if we definitely want a separate topic and schema eventually anyway, should we just go ahead and create it now?

**Comment by untitaker** [comment]
> We are adding risk into our existing transactions pipeline

yes, multiple schemas per topic would solve this. there's not really a risk of one consumer group impacting another if they do not share a schema

**Comment by lynnagara** [comment]
@untitaker In this case, I don't think they should even be sharing a topic at all though. My understanding is that's a shortcut we are taking right now.

**Comment by untitaker** [comment]
Currently it's only sentry-kafka-schemas that makes this dangerous. I don't think there's any other reason to split out topics right now

**Comment by lynnagara** [comment]
It isn't sentry-kafka-schemas that makes it dangerous though, as we are currently not enforcing the schema. I'm actually more worried about the changes we are doing in consumers and producers.

**Review by lynnagara — APPROVED** [review]

**Pull request merged**
