### PR TITLE
feat(replays): Add version field

### PR DESCRIPTION
**Pull request by cmanallen**

### CODE REVIEW

**Comment by cmanallen** [comment]
cc @untitaker

**Comment by cmanallen** [comment]
> This PR contains breaking changes. 

Does it though?  Its a new field with a default value?  Surely this won't impact producer or consumer.  The field would just be ignored.

**Comment by untitaker** [comment]
> Does it though? Its a new field with a default value? Surely this won't impact producer or consumer. The field would just be ignored.

We are currently considering this a breaking change because previously the schema allowed you to send any type for `version`, and now it's no longer valid to send a string for `version`.

It would not be considered a breaking change if `additionalProperties=false`.

We are still figuring this out... for now I'd suggest to ignore it. This is why it's not a required check anyway

**Review by untitaker — APPROVED** [review]

**Comment by cmanallen** [comment]
@untitaker How long until a new tag is created?

**Comment by untitaker** [comment]
@cmanallen PTAL at the bottom of the README. You can kick off a github action to start the release process

**Pull request merged**
